import './globals.css';
import Header from "./components/Header/Header";

export const metadata = {
  title: "My-Movie-App",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <Header />
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
